### ISSUE TITLE
cuda arch problem when building ms_deform_im2col

### ISSUE THREAD

**Issue by jylink** [Visual-Behavior/aloception#163]
I'm trying to convert deformable detr to trt, but got these errors when I run `load_trt_plugins_for_deformable_detr()` 

```
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.0.194
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Configurable variable TRT_LIB set to /root/TensorRT-8.0.3.4/lib
-- Configurable variable TRT_INCLUDE set to /root/TensorRT-8.0.3.4/include
-- Configurable variable CUDA_INC_DIR set to /usr/local/cuda/include
-- Configurable variable CUDA_ARCH_SM set to 70

The following variables are derived from the values of the previous variables unless provided explicitly:

-- Configurable variable NVINFER_LIB set to /root/TensorRT-8.0.3.4/lib/libnvinfer.so
-- CUDA_INC_DIR: /usr/local/cuda/include
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/build
Scanning dependencies of target ms_deform_im2col_trt
[ 25%] Building CUDA object CMakeFiles/ms_deform_im2col_trt.dir/sources/ms_deform_im2col_kernel.cu.o
[ 50%] Building CXX object CMakeFiles/ms_deform_im2col_trt.dir/sources/ms_deform_im2col_plugin.cpp.o
/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(87): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(87): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(88): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(88): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(89): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(89): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(89): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(89): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(100): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(100): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(100): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(100): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(106): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(106): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(112): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(112): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(124): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(126): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(245): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(245): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(246): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(246): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(248): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(248): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(248): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(248): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(248): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(248): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(250): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(250): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(221): warning: variable "q_col" was declared but never referenced

/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu(155): warning: variable "q_col" was declared but never referenced

44 errors detected in the compilation of "/root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/sources/ms_deform_im2col_kernel.cu".
CMakeFiles/ms_deform_im2col_trt.dir/build.make:62: recipe for target 'CMakeFiles/ms_deform_im2col_trt.dir/sources/ms_deform_im2col_kernel.cu.o' failed
make[2]: *** [CMakeFiles/ms_deform_im2col_trt.dir/sources/ms_deform_im2col_kernel.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ms_deform_im2col_trt.dir/all' failed
make[1]: *** [CMakeFiles/ms_deform_im2col_trt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
/root/Deformable-DETR-ult-trt
Traceback (most recent call last):
  File "trt_convert.py", line 28, in <module>
    load_trt_plugins_for_deformable_detr()
  File "/root/Deformable-DETR-ult-trt/alonet/deformable_detr/trt_exporter.py", line 42, in load_trt_plugins_for_deformable_detr
    load_trt_custom_plugins(MS_DEFORM_IM2COL_PLUGIN_LIB)
  File "/root/Deformable-DETR-ult-trt/alonet/torch2trt/utils.py", line 26, in load_trt_custom_plugins
    ctypes.CDLL(lib_path)
  File "/root/miniconda3/envs/ljy/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/Deformable-DETR-ult-trt/alonet/torch2trt/plugins/ms_deform_im2col/build/libms_deform_im2col_trt.so: cannot open shared object file: No such file or directory
```

It looks like a cuda arch problem but my gpu compute capability looks fine...

FYI
```
Device 0: "Tesla V100-SXM2-32GB"
  CUDA Driver Version / Runtime Version          11.0 / 11.0
  CUDA Capability Major/Minor version number:    7.0

cuda 11.0.194
cudnn 8.2.1.32
tensorrt 8.0.3.4
cmake 3.10.2
pycuda 2020.1
onnx 1.10.2
```

**Comment by jylink** [comment]
fixed, `set_ifndef(CUDA_ARCH_SM 70)` is not enough, nvcc gencode flags are required

```
### alonet/torch2trt/plugins/ms_deform_im2col/CMakeLists.txt

set_ifndef(CUDA_ARCH_SM 70) # should be fine for Tesla V100

...

# Link TensorRT's nvinfer lib
target_link_libraries(ms_deform_im2col_trt PRIVATE ${NVINFER_LIB})

# NEW
target_compile_options(ms_deform_im2col_trt PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:
-gencode=arch=compute_70,code=sm_70  
>)
```
